- name: Create K8s User
  hosts: 'k8scontrollers, k8sworkers'
  become: true
  tasks:
   - name: 'Create user account'
     ansible.builtin.user: # name=kube append=yes state=present createhome=yes shell=/bin/bash
      name: kube
      append: true
      state: present
      createhome: true
      groups: wheel
      shell: /bin/bash

   - name: Allow 'kube' to use sudo without needing a password
     ansible.builtin.lineinfile:
      dest: /etc/sudoers
      line: 'kube ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

   - name: Set up authorized keys for the kube user
     ansible.posix.authorized_key: # user=kube key="{{item}}"
      user: kube
      key: "{{ item }}"
     with_file:
      - ~/.ssh/id_rsa.pub
