- name: Kubeadm Init
  hosts: 'k8scontrollers'
  remote_user: kube
  become: true
  become_method: sudo
  tasks:
   - name: Open Firewall Ports (1/2)
     ansible.posix.firewalld:
      port: 6443/tcp
      permanent: true
      immediate: true
      state: enabled
   - name: Open Firewall Ports (2/2)
     ansible.posix.firewalld:
      port: 10250/tcp
      permanent: true
      immediate: true
      state: enabled

   - name: Check Component Status
     become: false
     ansible.builtin.command:
      cmd: kubectl get cs
     register: kubecs
     ignore_errors: true
     no_log: true
     changed_when: false
   - name: Kubeadm init
     ansible.builtin.command:
      cmd: "kubeadm init --apiserver-advertise-address={{ ansible_ssh_host }} --control-plane-endpoint={{ ansible_ssh_host }}"
     changed_when: true
     when: '"refused" in kubecs.stderr'

   - name: Create kube dir in home
     ansible.builtin.file:
      path: /home/kube/.kube
      state: directory
      owner: kube
      mode: '0755'
     when: '"refused" in kubecs.stderr'
   - name: Wait for kube config to exist
     ansible.builtin.wait_for:
      path: /etc/kubernetes/admin.conf
     when: '"refused" in kubecs.stderr'
   - name: Copy kube config
     ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      remote_src: true
      dest: /home/kube/.kube/config
      owner: kube
      mode: '0644'
     when: '"refused" in kubecs.stderr'
   - name: Wait 1 minute for safety
     ansible.builtin.pause:
      minutes: 1
