---
# defaults file for k8s

# Cri-O Vars
stable_repo: |
  [devel_kubic_libcontainers_stable]
  name=Stable Releases of Upstream github.com/containers packages (CentOS_8_Stream)
  type=rpm-md
  baseurl=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/
  gpgcheck=1
  gpgkey=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/repodata/repomd.xml.key
  enabled=1
crio_repo: |
  [devel_kubic_libcontainers_stable_cri-o_1.26]
  name=devel:kubic:libcontainers:stable:cri-o:1.26 (CentOS_8_Stream)
  type=rpm-md
  baseurl=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/CentOS_8_Stream/
  gpgcheck=1
  gpgkey=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/CentOS_8_Stream/repodata/repomd.xml.key
  enabled=1
crio_version: 1.26*

# Kube Vars
kube_repo: |
  [kubernetes]
  name=Kubernetes
  baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
  enabled=1
  gpgcheck=1
  gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  exclude=kubelet kubeadm kubectl
kube_version: 1.26*