apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallbAddressPool
  namespace: metallb
spec:
  addresses:
  - 192.168.56.150-192.168.56.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - metallbAddressPool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: control-01
  - matchLabels:
      kubernetes.io/hostname: worker-01
  - matchLabels:
      kubernetes.io/hostname: worker-02