- hosts: k8sworkers, k8scontrollers
  remote_user: "{{user}}"
  roles:
    - role: ../roles/ingress-nginx-ports
      message: Opening Ports for Ingress NGINX
      become: true
      become_method: sudo

- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/ingress-nginx
      message: Installing Ingress NGINX