- import_playbook: ./plays/k8s-install.yaml

- import_playbook: ./plays/metallb-install.yaml

- hosts: k8sworkers, k8scontrollers
  remote_user: "{{user}}"
  roles:
    - role: ../roles/nfs-utils
      message: Installing nfs-utils package
      become: true
      become_method: sudo


- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/nfs-provisioner
      message: Installing NFS Provisioner