---
# tasks file for ca-trust

- name: Check current cert's existance
  ansible.builtin.set_fact:
    new_crt: "{{ hostvars['CA_CRT']['cmd'] }}"
    new_crt_encoded: "{{ hostvars['CA_CRT']['cmd'] | b64encode }}"

- name: Check current cert's existance
  ansible.builtin.stat:
    path: "/etc/pki/ca-trust/source/anchors/{{ certificateName | mandatory }}.crt"
  register: ca_crt_stat

- name: Slurp current Crt
  ansible.builtin.slurp:
    src: "/etc/pki/ca-trust/source/anchors/{{ certificateName | mandatory }}.crt"
  register: ca_crt
  when: ca_crt_stat.stat.exists

- name: Ensures /etc/pki/ca-trust/source/anchors/ dir exists
  file: 
    path: "/etc/pki/ca-trust/source/anchors/"
    state: directory

- block:
  - name: Install ca-certificates
    ansible.builtin.yum:
      name:
        - ca-certificates
      disable_excludes: all
      state: present
  - name: Enabled CA trust
    ansible.builtin.command:
      cmd: update-ca-trust force-enable
  - name: Create crt file
    ansible.builtin.copy:
      content: "{{ new_crt }}"
      dest: "/etc/pki/ca-trust/source/anchors/{{ certificateName | mandatory }}.crt"
  - name: Extract CA Trust
    ansible.builtin.command:
      cmd: update-ca-trust extract
  when:
    - not ca_crt_stat.stat.exists or ca_crt.content != new_crt_encoded