apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallbaddresspool
  namespace: metallb
spec:
  addresses:
  - 10.0.3.50-10.0.3.100
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - metallbaddresspool