---
# tasks file for update-kubeadm-control

# kubeadm
- name: Add K8s Repo and exclude kube apps from update
  ansible.builtin.copy:
    dest: '/etc/yum.repos.d/kubernetes.repo'
    content: |
        {{kubernetesRepoFileContents | mandatory}}
    mode: '0644'
    follow: yes
  changed_when: true

- name: Update Kubeadm
  ansible.builtin.yum:
    name:
      - "kubeadm-{{kubeVersion | mandatory}}"
    disable_excludes: all
    state: present

- name: Apply Upgrade
  ansible.builtin.command:
    cmd: "kubeadm upgrade apply -y v{{kubeVersion}}"
  changed_when: true
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

