---
# tasks file for flannel
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: https://flannel-io.github.io/flannel/

- name: Create a kube-flannel namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: kube-flannel
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

- name: Install Flannel
  kubernetes.core.helm:
    name: flannel
    namespace: kube-flannel
    chart_ref: flannel/flannel
    chart_version: "{{flannelChartVersion}}"
    set_values:
      - value: podCidr="10.244.0.0/16"
        valueType: string

# - name: Restart CRI-O service
#   become: true
#   become_method: sudo
#   ansible.builtin.systemd:
#     name: crio
#     state: restarted
#     daemon_reload: true
# - name: Restart k8s service
#   become: true
#   become_method: sudo
#   ansible.builtin.systemd:
#     name: kubelet
#     state: restarted
#     daemon_reload: true

- name: Wait for safety
  ansible.builtin.pause:
   seconds: 15