---
# tasks file for flannel-recycle

- name: Restart all flannel pods
  ansible.builtin.shell:
    cmd: "kubectl delete pods --selector=app=flannel -n=kube-flannel"
  environment:
    KUBECONFIG: "/home/{{user|mandatory}}/.kube/config"


- name: Wait 2 minute for safety (Flannel has to stand up)
  ansible.builtin.pause:
    minutes: 2