---
# tasks file for drain-node


- name: Drain Node {{ node }} On Node
  ansible.builtin.command:
   cmd: kubectl drain {{ node }} --ignore-daemonsets --delete-emptydir-data --force --grace-period=10
  changed_when: true
  when: runLocal is undefined

- name: Drain Node {{ node }} Locally
  ansible.builtin.command:
   cmd: kubectl drain {{ node }} --ignore-daemonsets --delete-emptydir-data --force --grace-period=10
  changed_when: true
  delegate_to: localhost
  when: runLocal is defined

# Todo: empty out the hashicorp vault namespace of pods or you'll be stuck open forever!