
# Configure Prerequisites
- name: Update Modules K8s config
  ansible.builtin.copy:
    dest: '/etc/modules-load.d/k8s.conf'
    content: |
        overlay
        br_netfilter
    mode: '0777'
  changed_when: true
- name: Modeprobe OverlayFS
  community.general.modprobe:
    name: overlay
- name: Modeprobe BRNetFilter
  community.general.modprobe:
    name: br_netfilter

- name: Update Sysctl K8s config
  ansible.builtin.copy:
    dest: '/etc/sysctl.d/k8s.conf'
    content: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
    mode: '0777'
  changed_when: true
- name: Apply sysctl
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: true

# Install
- name: Install CRI-O (1/3) - Add stable repo
  ansible.builtin.copy:
    dest: '/etc/yum.repos.d/crio-stable.repo'
    content: |
      {{stable_repo}}
    mode: '0644'
    follow: yes
  changed_when: true
- name: Install CRI-O (2/3) - Add CRI-O repo
  ansible.builtin.copy:
    dest: '/etc/yum.repos.d/crio.repo'
    content: |
      {{crio_repo}}
    mode: '0644'
    follow: yes
  changed_when: true
- name: Install CRI-O (3/3) - YUM Install
  ansible.builtin.yum:
    name:
      - cri-o-{{crio_version}}
      - containernetworking-plugins
    disable_excludes: all
    state: present
- name: Enable CRI-O service
  ansible.builtin.systemd:
    name: crio
    enabled: true
    state: started
