apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-catalog-helm
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rts-core/app-catalog.git
    path: root-helm/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true