---
- name: Create a ingress namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ ingressNamespace }}"
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

- name: Install ingress
  kubernetes.core.helm:
    name: "{{ ingressName }}"
    namespace: "{{ ingressNamespace }}"
    chart_ref: ingress-nginx
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_version: "{{ chartVersion }}"
    set_values:
      - value: crds.validationFailurePolicy=Ignore
        valueType: string
      - value: controller.ingressClass={{ ingressClass }}
        valueType: string
      - value: controller.ingressClassResource.name={{ ingressClass }}
        valueType: string
      - value: controller.ingressClassResource.controllerValue=k8s.io/{{ ingressClass }}
        valueType: string
      - value: controller.ingressClassResource.default=false
        valueType: boolean
      - value: controller.extraArgs.enable-ssl-passthrough=true
        valueType: string

- name: Remove auth hook
  kubernetes.core.k8s:
    state: absent
    api_version: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name: ingress-nginx-admission

- name: Wait for safety
  ansible.builtin.pause:
   seconds: 120