# Vault
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../../roles/vault/install
      message: Installing Hashicorp Vault
      helmChartVersion: "{{ vaultHelmChartVersion }}"
      helmValues: "{{ lookup('file', '{{ vaultHelmValuesPath }}' ) | from_yaml}}"
      openSSLConf: "{{ lookup('file', '{{ vaultOpenSSLConfPath }}' ) }}"
      certificateSecretNamespace: cert-manager
      certificateSecretName: nginx-ca-secret
      certificateName: "{{ selfSignedCertificateName }}"
      ingressDefinition: "{{ lookup('file', '{{ vaultIngressPath }}' ) }}"
      certificateDefinition: "{{ lookup('file', '{{ vaultCertificatePath }}' ) }}"
    - role: ../../roles/vault/unseal
      message: Unsealing Hashicorp Vault
      become: true
      become_method: sudo
      replicaCount: 1
    - role: ../../roles/wait
      message: Waiting 20 Seconds for Safety
      waitSeconds: 20
    - role: ../../roles/vault/unseal
      message: Retrying Unsealing Hashicorp Vault for Safety
      become: true
      become_method: sudo
      replicaCount: 1
    - role: ../../roles/vault/k8s-auth
      message: Setting up K8s Auth
      tokenReviewerDefinition: "{{ lookup('file', '{{ vaultTokenReviewerPath }}' ) }}"