# Vault
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../../roles/hashicorp-vault-install
      message: Installing Hashicorp Vault
      helmChartVersion: "{{ vaultHelmChartVersion }}"
      helmValues: "{{ lookup('file', '{{ vaultHelmValuesPath }}' ) | from_yaml}}"
      openSSLConf: "{{ lookup('file', '{{ vaultOpenSSLConfPath }}' ) }}"
      certificateSecretNamespace: cert-manager
      certificateSecretName: nginx-ca-secret
      certificateName: "{{ selfSignedCertificateName }}"
      ingressDefinition: "{{ lookup('file', '{{ vaultIngressPath }}' ) }}"
      certificateDefinition: "{{ lookup('file', '{{ vaultCertificatePath }}' ) }}"
      tokenReviewerDefinitions: "{{ lookup('file', '{{ vaultTokenReviewerPath }}' ) }}"
    - role: ../../roles/vault-unseal
      message: Unsealing Hashicorp Vault
      become: true
      become_method: sudo
      replicaCount: 1
    - role: ../../roles/vault-join
      message: Joining Hashicorp Vault nodes
      initialLeaderHostname: "{{ vaultInitialLeaderHostname }}"
      replicaCount: "{{ vaulReplicaCount }}"
    - role: ../../roles/vault-unseal
      message: Unsealing Hashicorp Vault
      become: true
      become_method: sudo
      replicaCount: "{{ vaulReplicaCount }}"