- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../../roles/vault/k8s-auth
      message: Setting up K8s Auth for Vault
      become: true
      become_method: sudo
      replicaCount: "{{ vaulReplicaCount }}"