---
# tasks file for update-k8s


# Crio
- name: Install CRI-O (1/3) - Add stable repo
  ansible.builtin.copy:
    dest: '/etc/yum.repos.d/crio-stable.repo'
    content: |
      {{crioStableRepoFileContents | mandatory}}
    mode: '0644'
    follow: yes
  changed_when: true
- name: Install CRI-O (2/3) - Add CRI-O repo
  ansible.builtin.copy:
    dest: '/etc/yum.repos.d/crio.repo'
    content: |
      {{crioRepoFileContents | mandatory}}
    mode: '0644'
    follow: yes
  changed_when: true
- name: Install CRI-O (3/3) - YUM Install
  ansible.builtin.yum:
    name:
      - cri-o-{{crioVersion | mandatory}}
      - containernetworking-plugins
    disable_excludes: all
    state: present
- name: Restart Cri-o
  ansible.builtin.service:
    name: crio
    daemon_reload: true
    state: restarted

# K8s
- name: Add K8s Repo and exclude kube apps from update
  ansible.builtin.copy:
    dest: '/etc/yum.repos.d/kubernetes.repo'
    content: |
        {{kubernetesRepoFileContents | mandatory}}
    mode: '0644'
    follow: yes
  changed_when: true

- name: Install K8s
  ansible.builtin.yum:
    name:
      - "kubelet-{{kubeVersion | mandatory}}"
      - "kubectl-{{kubeVersion | mandatory}}"
    disable_excludes: all
    state: present

- name: Restart Kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted