---
# tasks file for flannel

- name: Add helm repo
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: https://flannel-io.github.io/flannel/

- name: Install net-tools
  ansible.builtin.yum:
    name:
      - net-tools
    disable_excludes: all
    state: present  

- name: Get Interface Name
  ansible.builtin.shell:
    cmd: "netstat -ie | grep -B1 '{{ansible_ssh_host}}' | head -n1 | awk -F [:] '{print $1}'"
  register: iface_name
  environment:
    KUBECONFIG: "/home/{{user|mandatory}}/.kube/config"

- name: Create a kube-flannel namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: kube-flannel
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

- name: Install Flannel
  kubernetes.core.helm:
    name: flannel
    namespace: kube-flannel
    chart_ref: flannel/flannel
    chart_version: "{{flannelChartVersion}}"
    values:
      podCidr: "10.244.0.0/16"
      podCidrv6: ""
      flannel:
        image:
          repository: docker.io/flannel/flannel
          tag: "v{{flannelChartVersion}}"
        image_cni:
          repository: docker.io/flannel/flannel-cni-plugin
          tag: v1.2.0
        args:
        - "--ip-masq"
        - "--kube-subnet-mgr"
        - "--iface={{iface_name.stdout}}"
        backend: "vxlan"
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

- name: Wait for safety
  ansible.builtin.pause:
   seconds: 15