---
# tasks file for flannel
- name: Download metrics-server manifest to the cluster.
  ansible.builtin.get_url:
    url: "{{flannel_url}}"
    dest: /tmp/flannel.yaml
    mode: '0664'

- name: Apply metrics-server manifest to the cluster.
  kubernetes.core.k8s:
    state: present
    src: /tmp/flannel.yaml

- name: Remove yaml
  delegate_to: localhost
  ansible.builtin.file:
    path: /tmp/flannel.yaml
    state: absent

- name: Restart CRI-O service
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    name: crio
    state: restarted
    daemon_reload: true
- name: Restart k8s service
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true

- name: Wait for safety
  ansible.builtin.pause:
   seconds: 15