# Argo-CD
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../../roles/argocd/setup-service-catalog
      message: Installing Service Catalog
      helmChartRepo: "{{ serviceCatalogHelmChartRepo }}"      