# Argo-CD
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/vault/k8s-auth
      message: Setting up K8s Auth
      tokenReviewerDefinition: "{{ lookup('file', '{{ vaultTokenReviewerPath }}' ) }}"