# Vault
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/hashicorp-vault-update
      message: Installing Hashicorp Vault
      helmChartVersion: "{{ vaultHelmChartVersion }}"
      helmValues: "{{ lookup('file', '{{ vaultHelmValuesPath }}' ) | from_yaml}}"
      openSSLConf: "{{ lookup('file', '{{ openSSLConfPath }}' ) }}"
      certificateSecretNamespace: cert-manager
      certificateSecretName: nginx-ca-secret
      certificateName: "{{ selfSignedCertificateName }}"
      become: true
      become_method: sudo

# - hosts: k8scontrollers[0]
#   remote_user: "{{user}}"
#   roles:
#     - role: ../roles/coredns-restart
#       message: Restarting kube-dns app