# Nginx Ingress
- hosts: k8sworkers, k8scontrollers
  remote_user: "{{user}}"
  roles:
    - role: ../roles/ingress-nginx-ports
      message: Opening Ports for Ingress NGINX
      become: true
      become_method: sudo
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    # - role: ../roles/ingress-nginx
    #   message: Installing External Ingress NGINX
    #   vars:
    #     ingressName: ingress-nginx-{{externalIngressName}}
    #     ingressNamespace: ingress-nginx-{{externalIngressName}}
    #     ingressClass: nginx-{{externalIngressName}}
    - role: ../roles/ingress-nginx
      message: Installing Internal Ingress NGINX
      vars:
        ingressName: ingress-nginx-{{internalIngressName}}
        ingressNamespace: ingress-nginx-{{internalIngressName}}
        ingressClass: nginx-{{internalIngressName}}

# # Nginx Ingress
# - hosts: k8sworkers, k8scontrollers
#   remote_user: "{{user}}"
#   roles:
#     - role: ../roles/ingress-nginx-ports
#       message: Opening Ports for Ingress NGINX
#       become: true
#       become_method: sudo
# - hosts: k8scontrollers[0]
#   remote_user: "{{user}}"
#   roles:
#     - role: ../roles/ingress-nginx
#       message: Installing External Ingress NGINX
#       vars:
#         ingressName: ingress-nginx-{{externalIngressName}}
#         ingressNamespace: ingress-nginx-{{externalIngressName}}
#         ingressClass: nginx-{{externalIngressName}}
#     - role: ../roles/ingress-nginx
#       message: Installing Internal Ingress NGINX
#       vars:
#         ingressName: ingress-nginx-{{internalIngressName}}
#         ingressNamespace: ingress-nginx-{{internalIngressName}}
#         ingressClass: nginx-{{internalIngressName}}