# K8s
- import_playbook: ./k8s/install.yaml

# Certs
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/jq
      message: Install jq
      become: true
      become_method: sudo
    - role: ../roles/ca-create
      message: Creating self signed certificate authority
    - role: ../roles/get-self-signed-cert
      message: Getting self signed cert
      certificateName: "{{ selfSignedCertificateName }}"
- hosts: k8scontrollers, k8sworkers
  remote_user: "{{user}}"
  roles:
    - role: ../roles/ca-trust
      message: Trusting CA Certificate
      certificateName: "{{ selfSignedCertificateName }}"
      become: true
      become_method: sudo
    - role: ../roles/nfs-utils
      message: Installing nfs-utils package
      become: true
      become_method: sudo