# K8s
- import_playbook: ./k8s-install.yaml

# MetalLB
- import_playbook: ./metallb-install.yaml

# NFS Storage
- hosts: k8sworkers, k8scontrollers
  remote_user: "{{user}}"
  roles:
    - role: ../roles/nfs-utils
      message: Installing nfs-utils package
      become: true
      become_method: sudo
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/nfs-provisioner
      message: Installing NFS Provisioner

# Certificate Manager
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/jq
      message: Install jq
      become: true
      become_method: sudo
    - role: ../roles/cert-manager
      message: Installing Cert-Manager
      vars:
        version: "{{certManagerVersion}}"
    - role: ../roles/ca-create
      message: Creating self signed certificate authority
    - role: ../roles/self-signed-issuer-create
      message: Creating self signed cert-manager issuer

- hosts: k8scontrollers, k8sworkers
  remote_user: "{{user}}"
  roles:
    - role: ../roles/ca-trust
      message: Trusting CA Certificate
      become: true
      become_method: sudo