# K8s
- import_playbook: ./k8s-install.yaml

# MetalLB
- import_playbook: ./metallb-install.yaml

# NFS Storage
- hosts: k8sworkers, k8scontrollers
  remote_user: "{{user}}"
  roles:
    - role: ../roles/nfs-utils
      message: Installing nfs-utils package
      become: true
      become_method: sudo
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/nfs-provisioner
      message: Installing NFS Provisioner

# Nginx Ingress
- hosts: k8sworkers, k8scontrollers
  remote_user: "{{user}}"
  roles:
    - role: ../roles/ingress-nginx-ports
      message: Opening Ports for Ingress NGINX
      become: true
      become_method: sudo
- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: ../roles/ingress-nginx
      message: Installing External Ingress NGINX
      vars:
        ingressName: ingress-nginx-{{externalIngressName}}
        ingressNamespace: ingress-nginx-{{externalIngressName}}
        ingressClass: nginx-{{externalIngressName}}
    - role: ../roles/ingress-nginx
      message: Installing Internal Ingress NGINX
      vars:
        ingressName: ingress-nginx-{{internalIngressName}}
        ingressNamespace: ingress-nginx-{{internalIngressName}}
        ingressClass: nginx-{{internalIngressName}}