- hosts: k8sworkers, k8scontrollers
  roles:
    - role: ../roles/common
      message: Setting up common settings.
      become: yes
    - role: ../roles/nano
      message: Adding nano.
      become: yes