---
# tasks file for calico-firewall

# - name: Open Firewall Ports [Calico networking (BGP)]
#   ansible.posix.firewalld:
#    port: 179/tcp
#    permanent: true
#    immediate: true
#    state: enabled
# - name: Open Firewall Ports [Calico networking with VXLAN enabled]
#   ansible.posix.firewalld:
#    port: 4789/udp
#    permanent: true
#    immediate: true
#    state: enabled
# - name: Open Firewall Ports [Calico networking with Typha enabled]
#   ansible.posix.firewalld:
#    port: 5473/tcp
#    permanent: true
#    immediate: true
#    state: enabled
# - name: Open Firewall Ports [Calico networking with IPv4 Wireguard enabled]
#   ansible.posix.firewalld:
#    port: 51820/udp
#    permanent: true
#    immediate: true
#    state: enabled
# - name: Open Firewall Ports [Calico networking with IPv6 Wireguard enabled]
#   ansible.posix.firewalld:
#    port: 51821/udp
#    permanent: true
#    immediate: true
#    state: enabled
# - name: Open Firewall Ports [flannel networking (VXLAN)]
#   ansible.posix.firewalld:
#    port: 4789/udp
#    permanent: true
#    immediate: true
#    state: enabled
# - name: Open Firewall Ports [All]
#   ansible.posix.firewalld:
#    port: 443/tcp
#    permanent: true
#    immediate: true
#    state: enabled
# - name: Open Firewall Ports [All]
#   ansible.posix.firewalld:
#    port: 6443/tcp
#    permanent: true
#    immediate: true
#    state: enabled
# - name: Open Firewall Ports [etcd datastore]
#   ansible.posix.firewalld:
#    port: 2379/tcp
#    permanent: true
#    immediate: true
#    state: enabled
  
# - name: Firewall masquerade On
#   ansible.posix.firewalld:
#     masquerade: true
#     state: enabled
#     zone: public
#     permanent: true
#     immediate: true

# - name: IP Tables to fix CoreDNS issue
#   ansible.builtin.iptables:
#     chain: INPUT
#     protocol: tcp
#     destination_port: 6443
#     ctstate: NEW
#     jump: ACCEPT
#     comment: IP Tables to fix CoreDNS issue

# - name: IP Tables to fix CoreDNS issue
#   ansible.builtin.iptables:
#     chain: INPUT
#     protocol: tcp
#     destination_port: 443
#     ctstate: NEW
#     jump: ACCEPT
#     comment: IP Tables to fix CoreDNS issue

# - name: IP Tables to fix CoreDNS issue
#   ansible.builtin.iptables:
#     chain: FORWARD
#     protocol: tcp
#     destination_port: 6443
#     ctstate: NEW
#     jump: ACCEPT
#     comment: IP Tables to fix CoreDNS issue

# - name: IP Tables to fix CoreDNS issue
#   ansible.builtin.iptables:
#     chain: FORWARD
#     protocol: tcp
#     destination_port: 443
#     ctstate: NEW
#     jump: ACCEPT
#     comment: IP Tables to fix CoreDNS issue

