---
# tasks file for calico

- name: Add helm repo
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts/

- name: Create namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: tigera-operator
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

- name: Install Calico
  kubernetes.core.helm:
    name: calico
    namespace: tigera-operator
    chart_ref: projectcalico/tigera-operator
    chart_version: "{{calicoChartVersion}}"
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"


- name: Wait for safety
  ansible.builtin.pause:
   seconds: 60