---
# tasks file for manual-helm-install
- name: Create a namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ k8sNamespaceName | mandatory }}"
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

# Checkout repo
- name: Remove git directory
  ansible.builtin.file:
    path: /tmp/helm_repo
    state: absent

- name: Git clone stable repo on HEAD
  ansible.builtin.git:
    repo: "{{ helmChartRepo | mandatory }}"
    dest: /tmp/helm_repo

- name: Build helm dependencies
  ansible.builtin.command:
    cmd: helm dependency build /tmp/helm_repo
  changed_when: true
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

- name: Deploy chart from local path
  kubernetes.core.helm:
    name: "{{ helmAppName | mandatory }}"
    chart_ref: /tmp/helm_repo
    namespace: "{{ k8sNamespaceName | mandatory }}"
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

- name: Remove git directory
  ansible.builtin.file:
    path: /tmp/helm_repo
    state: absent

- name: Wait for safety
  ansible.builtin.pause:
    minutes: "{{ safetyDelayInMinutes }}"