- name: register status of /etc/kubernetes/pki/ca.crt
  stat:
    path: /etc/kubernetes/pki/ca.crt
  register: k8s_join_file

- name: Open Firewall Ports (1/4)
  when: "not k8s_join_file.stat.exists"
  ansible.posix.firewalld:
   port: 6443/tcp
   permanent: true
   immediate: true
   state: enabled
- name: Open Firewall Ports (2/4)
  when: "not k8s_join_file.stat.exists"
  ansible.posix.firewalld:
   port: 10250/tcp
   permanent: true
   immediate: true
   state: enabled
- name: Open Firewall Ports (3/4)
  when: "not k8s_join_file.stat.exists"
  ansible.posix.firewalld:
   port: 2379/tcp
   permanent: true
   immediate: true
   state: enabled
- name: Open Firewall Ports (4/4) [Flannel]
  when: "not k8s_join_file.stat.exists"
  ansible.posix.firewalld:
   port: 8472/udp
   permanent: true
   immediate: true
   state: enabled

- name: Join K8s
  when: "not k8s_join_file.stat.exists"
  ansible.builtin.command:
   cmd: "{{ hostvars['K8S_JOIN_COMMAND']['cmd'] }}"
   creates: /etc/kubernetes/pki/ca.crt
  changed_when: true

- name: Wait 5 minute for safety (Network has to stand up)
  ansible.builtin.pause:
    minutes: 5
