- hosts: k8scontrollers[0]
  remote_user: "{{user}}"
  roles:
    - role: .../../roles/k8s-get-join-token
      message: Getting join token
      become: true
      become_method: sudo

# Disabled as non-functional for now
# - hosts: k8scontrollers, !k8scontrollers[0]
#   remote_user: "{{user}}"
#   roles:
#     - role: ../roles/k8s-join-control
#       message: Joining K8s network
#       become: true
#       become_method: sudo

- hosts: k8sworkers
  remote_user: "{{user}}"
  roles:
    - role: ../../roles/k8s-join-worker
      message: Joining K8s network
      become: true
      become_method: sudo