---
# tasks file for cert-manager
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Create Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: cert-manager
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  environment:
    KUBECONFIG: "/home/{{user}}/.kube/config"

- name: Install Helm Chart
  kubernetes.core.helm:
    name: cert-manager
    namespace: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{version | mandatory}}"
    set_values:
      - value: installCRDs=true
        valueType: boolean
      - value: prometheus.enabled={{prometheusEnabled}}
        valueType: boolean