---
# tasks file for k8s-get-join-token
- name: Get Worker Join Command
  ansible.builtin.command:
   cmd: kubeadm token create --print-join-command
  register: kubeadmjoin
  changed_when: false
- name: "Add K8S Token and Hash to dummy host"
  ansible.builtin.add_host:
   name: "K8S_JOIN_COMMAND"
   cmd: "{{ kubeadmjoin.stdout }}"